### ISSUE TITLE
Books that start with numerals

### ISSUE THREAD

**Issue by SamejSpenser** [tim-hub/obsidian-bible-reference#50]
Hello @tim-hub.

First of all, congratulations for the excellent plugin. It is essential for my Bible studies! 😉

I'm Brazilian, and I use the _João Ferreira de Almeida_ version in the Obsidian Bible Reference settings. But when I need to insert some verse from books that start with a numbering, the plugin simply does not deliver any pop-up with the desired verse.

For example, **1 Timothy 6:10**: I already tried with `--1timoteo6:10`, `--Itimoteo6:10`, `--itimoteo6:10`, `--1 Timóteo 6:10`, `--I Timóteo 6:10`, `--i timóteo 6:10`, `--1Timóteo6:10`, `--ITimóteo6:10`, `--itimóteo6:10`, `--1 Timóteo 6.10`, `--1timoteo6.10`, `--1ti6:10`, `--1ti6.10`, `--1tim6:10`, `--1tim6.10`, `--Itim6.10`, etc.

I also tried using the name of the book in English, and the result was the same: no reference. Both the Old and New Testament books, as long as they begin with a numeral, have no reference.

Is this a bug, or am I the one who doesn't know how to use the plugin correctly? 🤔

Would it also be possible to add a command accessible through `Ctrl + P`, where we can insert the desired book and verse so that the plugin pastes it in the position where the cursor is?

Regards,
Samej Spenser.

**Comment by tim-hub** [comment]
Surely this is a bug.

Thanks for the feedback, and `Ctrl+P`

That is a good idea.

**Comment by tim-hub** [comment]
Would u mind trying it in new version, 1.1.4

I found it works on my side now.

**Comment by SamejSpenser** [comment]
> Would u mind trying it in new version, 1.1.4
> 
> I found it works on my side now.

I installed `v1.1.4`. The bug still remains the same, without any change in what I reported earlier!

**Comment by jhonatasFernandes** [comment]
any updates in that bug? i loved the plugin, but cant use for that books...

**Comment by jhonatasFernandes** [comment]
As i've said, i loved that plugin... So, I started debuggin the code, and i figure out what was buggin it.
1. var shortReg was getting only Chapters with 3 or more letters, so i changed it
2. const bookName was getting only Chapters with 3 or more letters, so i changed it
3. the https://bible-api.com API need a space to be between the book number and name, so i created an "if" to check if the book starts with a number, then put a space there
4. then i change the "const chapterNumber" to const chapterNumber = parseInt(numbers[0].toString().replace(/^\D+/g, "")), to clean the number in the chapter part.

I didnt tested it in all options avaliable, but i think the code bellow could help (i commented what have been changed)

[obsidian-bible-reference.zip](https://github.com/tim-hub/obsidian-bible-reference/files/9466401/obsidian-bible-reference.zip)

**Comment by jhonatasFernandes** [comment]
sorry, i don't know how to do that... i actually dont use github haha
here is the main.js that i changed:

ps: i also changed the verse design to be as the print bellow
[main.zip](https://github.com/tim-hub/obsidian-bible-reference/files/9480598/main.zip)
![image](https://user-images.githubusercontent.com/72778921/188223490-aa8cfa06-c51f-4ba7-ae0c-86b0264b8c73.png)

**Comment by SamejSpenser** [comment]
I edited the CSS of the callouts to display a bible icon when I insert the “![Bible]” snippet, and the result is this one from the print.

![image](https://user-images.githubusercontent.com/14796034/188239693-b9382f13-2ad6-4226-a2a5-f6f7340857b5.png)

**Comment by tim-hub** [comment]
> I edited the CSS of the callouts to display a bible icon when I insert the “`![Bible]`” snippet, and the result is this one from the print.
> 
> ![image](https://user-images.githubusercontent.com/14796034/188239693-b9382f13-2ad6-4226-a2a5-f6f7340857b5.png)
> 

This is actually quite nice.

It will be great that making a PR for it. 😂


Otherwise I will try find a time to make the changes.

**Comment by SamejSpenser** [comment]
> This is actually quite nice.
> 
> It will be great that making a PR for it. joy
> 
> Otherwise I will try find a time to make the changes.

I'm very happy to know that you liked it. 😃

I'm not a programmer and, like @jhonatasFernandes, I don't know how to make a pull request. I'm sorry. 😅

What I did there was insert the Bible icon as a CSS snippet in the snippets folder under `.obsidian`. As for the book name, chapter and verse I manually moved up, simply `Ctrl + X` / `Ctrl + V`.

Here's the snippet I used for the icon:

```css
/* Add “Bible” Icon to Callouts */

.callout[data-callout="bible"] {
    --callout-icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><!--! Font Awesome Pro 6.1.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M448 336v-288C448 21.49 426.5 0 400 0H96C42.98 0 0 42.98 0 96v320c0 53.02 42.98 96 96 96h320c17.67 0 32-14.33 32-31.1c0-11.72-6.607-21.52-16-27.1v-81.36C441.8 362.8 448 350.2 448 336zM144 144c0-8.875 7.125-15.1 16-15.1L208 128V80c0-8.875 7.125-15.1 16-15.1l32 .0009c8.875 0 16 7.12 16 15.1V128L320 128c8.875 0 16 7.121 16 15.1v32c0 8.875-7.125 16-16 16L272 192v112c0 8.875-7.125 16-16 16l-32-.0002c-8.875 0-16-7.127-16-16V192L160 192c-8.875 0-16-7.127-16-16V144zM384 448H96c-17.67 0-32-14.33-32-32c0-17.67 14.33-32 32-32h288V448z"/></svg>';
}
```
